preload = /home/mateus/Images/Wallpapers/bay.JPG
preload = /home/mateus/Images/Wallpapers/samori.jpg
preload = /home/mateus/Images/Wallpapers/hands.jpg
preload = /home/mateus/Images/Wallpapers/space.jpg
preload = /home/mateus/Images/Wallpapers/dschneider.jpg
preload = /home/mateus/Images/Wallpapers/jeeokp.jpg
preload = /home/mateus/Images/Wallpapers/christmas1.jpg

wallpaper {
    monitor = 
    path = /home/mateus/Images/Wallpapers/train2.jpg
    fit_mode = cover
}

# wallpaper {
#     monitor = HMDI-A-1
#     path = /home/mateus/Images/Wallpapers/space.jpg 
#     fit_mode = cover
# }


